include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # Disable conflicting rules
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    
    # Additional rules for better code quality
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false # Allow prints for debugging
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    prefer_relative_imports: true
    always_use_package_imports: false
    sort_constructors_first: true
    # Keep logical grouping in pubspec instead of flat alphabetical ordering
    sort_pub_dependencies: false
    use_key_in_widget_constructors: true
    
    # Arabic/RTL specific rules
    avoid_escaping_inner_quotes: true
    prefer_interpolation_to_compose_strings: true
    
    # Performance rules
    avoid_function_literals_in_foreach_calls: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_spread_collections: true
    
    # Style rules
    curly_braces_in_flow_control_structures: true
    flutter_style_todos: true
    require_trailing_commas: true
    
    # Error prevention
    avoid_empty_else: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true
    literal_only_boolean_expressions: false
    no_adjacent_strings_in_list: true
    prefer_void_to_null: true
    unawaited_futures: true
    unnecessary_statements: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/generated/**"
    - "lib/generated/**"
    - "build/**"
    - ".dart_tool/**"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  plugins:
    - dart_code_metrics