arb-dir: assets/translations
template-arb-file: ar.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/core/localization/generated
nullable-getter: false
preferred-supported-locales: ['ar', 'en']
use-deferred-loading: false
