// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLrsyeN9AUbhBXNhhwKaaD4RqGXLXp250',
    appId: '1:370645054085:web:c42e7fac8e38d4e164efec',
    messagingSenderId: '370645054085',
    projectId: 'fir-networkapp',
    authDomain: 'fir-networkapp.firebaseapp.com',
    storageBucket: 'fir-networkapp.firebasestorage.app',
    measurementId: 'G-DV8NGZ6HP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSmpAHcxeNOrlZE5SJXsqd_Hd5718cN2s',
    appId: '1:370645054085:android:efae1c54d62832a664efec',
    messagingSenderId: '370645054085',
    projectId: 'fir-networkapp',
    storageBucket: 'fir-networkapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1t6toBH9mRZq1jV4C8QOUMhzMQtc-ezI',
    appId: '1:370645054085:ios:4a9cf77b79c73fb164efec',
    messagingSenderId: '370645054085',
    projectId: 'fir-networkapp',
    storageBucket: 'fir-networkapp.firebasestorage.app',
    iosBundleId: 'com.example.networkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1t6toBH9mRZq1jV4C8QOUMhzMQtc-ezI',
    appId: '1:370645054085:ios:4a9cf77b79c73fb164efec',
    messagingSenderId: '370645054085',
    projectId: 'fir-networkapp',
    storageBucket: 'fir-networkapp.firebasestorage.app',
    iosBundleId: 'com.example.networkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLrsyeN9AUbhBXNhhwKaaD4RqGXLXp250',
    appId: '1:370645054085:web:0f9617c0850a0e6864efec',
    messagingSenderId: '370645054085',
    projectId: 'fir-networkapp',
    authDomain: 'fir-networkapp.firebaseapp.com',
    storageBucket: 'fir-networkapp.firebasestorage.app',
    measurementId: 'G-10KSBY4RH6',
  );
}
